@host = http://localhost:5261

### 1. Login
# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "Gendalf_grey",
  "password": "password"
}

### 1. Login
# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "123",
  "password": "123123"
}

### 1. Login
# @name login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "3673673567",
  "password": "123123"
}

### 2. Get user list
GET {{host}}/api/admin/users
Authorization: Bearer {{login.response.body.token}}

### Get specific user
GET {{host}}/api/admin/users/2
Authorization: Bearer {{login.response.body.token}}
Accept: application/json

###
GET {{host}}/api/admin/roles
Authorization: Bearer {{login.response.body.token}}
Accept: application/json

###
GET {{host}}/api/reference/departments
Authorization: Bearer {{login.response.body.token}}
Accept: application/json

###
GET {{host}}/api/devices
Authorization: Bearer {{login.response.body.token}}
Accept: application/json

###
GET {{host}}/api/devices/d5d5d5d5-d5d5-d5d5-d5d5-d5d5d5d5d5d5
Authorization: Bearer {{login.response.body.token}}
Accept: application/json

### 2. Update user
PATCH {{host}}/api/admin/users/7
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json
Accept: application/json

{
  "isActive": true,
  "roles": ["Admin"]
}
